myMvcAppTraining/myMvcAppTraining/Models/Employer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
namespace myMvcAppTraining.Models
{
    [Table("tblEmployer")]
    public class Employer
    {

        [Key]
        public int empId { get; set; }

        [DisplayName("FirstName")]
        [Required(ErrorMessage = "Please Provide Firstname")]
        public string empFirstname { get; set; }

        [Required(ErrorMessage = "Please Provide Middlename")]
        [DisplayName("MiddleName")]
        public string empMiddlename { get; set; }

        [Required(ErrorMessage = "Please Enter Lastname")]
        [DisplayName("LastName")]
        public string empLastname { get; set; }

        [Required(ErrorMessage = "Please Select Gender")]
        [DisplayName("Gender")]
        public string empGender { get; set; }

        [Required(ErrorMessage = "Please Provide Contact no")]
        [StringLength(10,MinimumLength=10, ErrorMessage = "Please Enter 10 Digit Contact No")]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Contact Number")]
        public string empContactno { get; set; }

        [Required(ErrorMessage = "Please Provide City")]
        [DisplayName("City")]
        public string empcity { get; set; }

        [Required(ErrorMessage = "Please Provide Description")]
        [DisplayName("Description")]
        public string empDescription { get; set; }

        [Required(ErrorMessage = "Please Enter Email")]
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid Email..Please Provide Valid Email")]
        public string empUsername { get; set; }

        [Required(ErrorMessage = "Please Provide Password")]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        public string empPassword { get; set; }

        [Required(ErrorMessage = "Please Select Company")]
        [DisplayName("Company")]
        public int companyId { get; set; }

        [ForeignKey("companyId")]
        public virtual Company Companys { get; set; }

    }
}

myMvcAppTraining/myMvcAppTraining/Controllers/EmployerController.cs
using myMvcAppTraining.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myMvcAppTraining.Controllers
{
    public class EmployerController : Controller
    {

        public ActionResult EmpList()
        {
            DBCon db = new DBCon();
            List<Employer> employers = db.employer.OrderBy(e => e.empFirstname).ToList();

            return View(employers);
        }

        public ActionResult EmpDetails(int empId)
        {
            DBCon db = new DBCon();
            Employer employer = new Employer();
            employer = db.employer.Single(m => m.empId == empId);
        
            return View(employer);
        }


        public ActionResult EmpCreate()
        {
            DBCon db = new DBCon();
            #region
            //EmployerDetails employerDetails = new EmployerDetails();
            //employerDetails.emp = db.employer.Single(m => m.empId == empId);
            //IEnumerable<SelectListItem> comList = db.company.Select(x => new SelectListItem()
            //{
            //    Value = x.companyId.ToString(),
            //    Text = x.name
            //});
            //employerDetails.companyList = comList;
            #endregion

            ViewBag.companyList = new SelectList(db.company, "companyId", "name");
            return PartialView("EmpCreatePartialView", new Employer());
        }

        [HttpPost]
        public ActionResult EmpCreate(Employer employer)
        {
            DBCon db = new DBCon();
          

            if (ModelState.IsValid)
            {
                #region add
                // Employer eFind = db.employer.Where(x => x.empUsername == employer.empUsername).First();
                //db.Entry(employer).State = EntityState.Added;
                //db.SaveChanges();
                #endregion add
                db.employer.Add(employer);
                db.SaveChanges();
                return RedirectToAction("EmpList");
            }
            #region
            //DBCon db = new DBCon();
            //EmployerDetails employerDetails = new EmployerDetails();
            //employerDetails.emp = db.employer.Single(m => m.empId == empId);
            //IEnumerable<SelectListItem> comList = db.company.Select(x => new SelectListItem()
            //{
            //    Value = x.companyId.ToString(),
            //    Text = x.name
            //});
            //employerDetails.companyList = comList;
            #endregion
            ViewBag.companyList = new SelectList(db.company, "companyId", "name");
            return new EmptyResult();
        }


        public ActionResult EmpEdit(int empId)
        {
            DBCon db = new DBCon();
            EmployerDetails employerDetails = new EmployerDetails();
            employerDetails.emp = db.employer.Single(m => m.empId == empId);
            IEnumerable<SelectListItem> comList = db.company.Select(x => new SelectListItem()
            {
                Value = x.companyId.ToString(),
                Text = x.name
            });
            employerDetails.companyList = comList;
            return PartialView("EmpEditPartialView", employerDetails);
            #region EmpEdit2
            //Employer emp= db.employer.Single(m => m.empId == empId);
            //ViewBag.ddl = new SelectList(db.company, "companyId", "name");
            //return PartialView("EditPartial", emp);
            #endregion

        }


        [HttpPost]
        public ActionResult EmpEdit(Employer emp)
        {
            DBCon db = new DBCon();
            //Employer emp = db.employer.Find(emp.empId);
            if (ModelState.IsValid)
            {
                db.Entry(emp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("EmpList");
            }
            return RedirectToAction("EmpEdit", emp.empId);
        }

        [HttpGet]
        public ActionResult EmpDelete(int empId)
        {
            DBCon db = new DBCon();
            //Employer empToDelete= db.employer.Single(x=> x.empId==empId);
            Employer empToDelete = db.employer.Find(empId);
            if (ModelState.IsValid)
            {
                db.employer.Remove(empToDelete);
                db.SaveChanges();
                return RedirectToAction("EmpList");
            }
            return View();
        }
    }
}

myMvcAppTraining/myMvcAppTraining/Views/Employer/EmpCreate1.cshtml
@model myMvcAppTraining.Models.Employer

@{
    ViewBag.Title = "EmpCreate";
}

@*<link href="~/Scripts/css/StyleSheetLoginForm.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<h2>EmpCreate</h2>

@using (Html.BeginForm("EmpCreate", "Employer", FormMethod.Post, new { id="createForm"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <legend>Employer</legend>
    <fieldset>

        <div class="editor-label">
            @Html.LabelFor(model => model.empFirstname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empFirstname)
            @Html.ValidationMessageFor(model => model.empFirstname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empMiddlename)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empMiddlename)
            @Html.ValidationMessageFor(model => model.empMiddlename)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empLastname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empLastname)
            @Html.ValidationMessageFor(model => model.empLastname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empGender)
        </div>
        <div class="editor-field">
            @*@Html.EditorFor(model => model.empGender)*@
            @Html.DropDownListFor(model => model.empGender, new List<SelectListItem>
                 {
                     new SelectListItem { Text = "Male", Value = "Male"},
                   new SelectListItem { Text ="Female", Value = "Female"}
                   }, "--Select Gender--")


            @Html.ValidationMessageFor(model => model.empGender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empContactno)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empContactno)
            @Html.ValidationMessageFor(model => model.empContactno)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empcity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empcity)
            @Html.ValidationMessageFor(model => model.empcity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empDescription)
            @Html.ValidationMessageFor(model => model.empDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empUsername)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empUsername)
            @Html.ValidationMessageFor(model => model.empUsername)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.empPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.empPassword)
            @Html.ValidationMessageFor(model => model.empPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.companyId)
        </div>
        <div class="editor-field">
           @* @Html.HiddenFor(model => model.companyId)*@
            @Html.DropDownListFor(model => model.companyId, (SelectList)ViewBag.companyList, "--Select Company--")
            @Html.ValidationMessageFor(model => model.companyId)
        </div>

        <p>
            <input type="submit" value="Create" id="btnCreate" />
            @*<input type="button" value="check" id="btncheck"/>*@
        </p>
    </fieldset>
}
@*<script>
    $(document).ready(function () {
        $("#btncheck").click(function () {
            var name = $("#@Html.IdFor(model => model.empFirstname)").val();
            alert(name);

        });
    });
</script>*@

myMvcAppTraining/myMvcAppTraining/Views/Employer/EmpDetails.cshtml
@model myMvcAppTraining.Models.Employer

@{
    ViewBag.Title = "EmpDetails";
}

<h2>Details</h2>

<fieldset>
    <legend>Employer</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empFirstname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empFirstname)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empMiddlename)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empMiddlename)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empLastname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empLastname)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empGender)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empGender)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empContactno)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empContactno)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empcity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empcity)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empUsername)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empUsername)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.empPassword)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.empPassword)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.companyId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Companys.name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "EmpEdit", new { empId = Model.empId }) |
    @Html.ActionLink("Back to List", "EmpList")
</p>

myMvcAppTraining/myMvcAppTraining/Views/Employer/EmpEdit1.cshtml
@model myMvcAppTraining.Models.EmployerDetails

@{
    ViewBag.Title = "EmpEdit";
}

<h2>Edit</h2>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

@using (Html.BeginForm("EmpEdit", "Employer", FormMethod.Post, new { id = "updateForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>EmployerDetails</legend>
        @Html.HiddenFor(model => model.emp.empId)

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empFirstname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empFirstname)
            @Html.ValidationMessageFor(model => model.emp.empFirstname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empMiddlename)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empMiddlename)
            @Html.ValidationMessageFor(model => model.emp.empMiddlename)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empLastname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empLastname)
            @Html.ValidationMessageFor(model => model.emp.empLastname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empGender)
        </div>
        <div class="editor-field">
           @* @Html.HiddenFor(model => model.emp.empGender)*@
            @Html.DropDownListFor(model => model.emp.empGender, new List<SelectListItem>
                 {
                     new SelectListItem { Text = "Male", Value = "Male"},
                   new SelectListItem { Text ="Female", Value = "Female"}
                   }, "--Select Gender--")
            @Html.ValidationMessageFor(model => model.emp.empGender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empContactno)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empContactno)
            @Html.ValidationMessageFor(model => model.emp.empContactno)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empcity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empcity)
            @Html.ValidationMessageFor(model => model.emp.empcity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empDescription)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empDescription)
            @Html.ValidationMessageFor(model => model.emp.empDescription)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empUsername)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empUsername)
            @Html.ValidationMessageFor(model => model.emp.empUsername)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.empPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.emp.empPassword)
            @Html.ValidationMessageFor(model => model.emp.empPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.emp.companyId)
        </div>
        <div class="editor-field">
            @*@Html.HiddenFor(model => model.emp.companyId)*@
           
            @Html.DropDownListFor(model => model.emp.companyId, Model.companyList, "--Select Company--")
            @*@Html.DropDownListFor(model => model.emp.companyId, (SelectList)ViewBag.ddl, "--Select Company--")*@
            @Html.ValidationMessageFor(model => model.emp.companyId)
        </div>

        <p>
            <input type="submit" value="Save"/>
        </p>
    </fieldset>
}

<div>
    @*@Html.ActionLink("Back to List", "EmpList")*@
</div>

myMvcAppTraining/myMvcAppTraining/Views/Employer/EmpList.cshtml
@model IEnumerable<myMvcAppTraining.Models.Employer>


@{
    ViewBag.Title = "Employer List";
  
}

<link href="~/Scripts/css/StyleSheetLoginForm.css" rel="stylesheet" />
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.8/jquery.validate.js" type="text/javascript"></script>
<script src="//ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.validate.unobtrusive.js" type="text/javascript"></script>

<p>
    <b>@Html.ActionLink("Register", "", null, new { @class = "buttonclass", @id = "linkAdd"})</b>
</p>
<h2>Employer List</h2>
<div align="center" style="font-family:'Times New Roman'" >
    <table class="classTableDesign" id="tblData">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.empFirstname)
                </th>
                <th>
                    @* @Html.DisplayNameFor(model => model.empMiddlename)*@
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.empLastname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.empGender)l
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.empContactno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.empcity)
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.empDescription)*@
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.empUsername)
                </th>
                <th>
                    @*  @Html.DisplayNameFor(model => model.empPassword)*@
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.companyId)
                    
                </th>
                <th></th>
            </tr>
        </thead>
    
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.empFirstname)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.empMiddlename)*@
                    @Html.HiddenFor(modelItem => item.empMiddlename)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empLastname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empGender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empContactno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empcity)
                </td>
                <td>
                    @* @Html.DisplayFor(modelItem => item.empDescription)*@
                    @Html.HiddenFor(modelItem => item.empDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.empUsername)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.empPassword)*@
                    @Html.HiddenFor(modelItem => item.empPassword)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Companys.name)
                </td>
                <td >
                    @*@Html.ActionLink("Edit", "EmpEdit", new { empId = item.empId }, new { @class = "buttonclass",@id="linkEdit" }) |*@
                    @Html.ActionLink("Edit", "EmpEdit", "Employer", new { empId = item.empId }, new { @class = "buttonEditclass buttonclassCurved", id = item.empId }) |
                    @Html.ActionLink("Details", "EmpDetails", new { empId = item.empId }, new { @class = "buttonclassCurved" }) |
                    @Html.ActionLink("Delete", "EmpDelete", new { empId = item.empId }, new { onclick = "return confirm('Are you Sure Want to delete the data')", @class = "buttonclassCurved" })

                </td>

            </tr>

        }

    </table>
</div>


<div id="divTable" style="display: none; font-family: 'Times New Roman'" class="divpopup"  ></div>

<script>


    $(document).ready(function () {
        $("tr:even").css("background-color", "#d9edf7");
       
        //Add new

        $("#linkAdd").click(function () {

            $("#divTable").dialog({
                resizable: true,
                dialogClass: 'alert-dialog',
                height: 700,
                width: 500,
                modal: true,
                open: function (event) {

                    @*$(this).load('@Url.Action("EmpCreate", "Employer")');*@
                    $(this).load("Employer/EmpCreate");
                },
                show: {

                    effect: "blind",
                    duration: 1000
                },

                title: "Add Employer",
                buttons: {
                    "Add": function () {
                        
                        var form = $("#createForm");
                        $.validator.unobtrusive.parse(form);                        
                        if (form.valid()) {
                           
                            addEmployer();
                            alert("Added Successfully....");
                            window.location = window.location.href;
                            location.reload();
                            $(this).dialog("close");
                            $("#divTable").empty();
                        }
                        
                       
                    }
                    ,
                    "Cancel": function () {
                       
                        $(this).dialog('close');
                    }
                }

            });
            return false;
        });

        //Edit

        $(".buttonEditclass").click(function () {
            var urlEdit = $(this).attr('href');
            var idx = $(this).attr('id');           
            $("#divTable").dialog({
                resizable: true,
                height: 700,
                width: 500,
                modal: true,
                open: function (event) {
                    //$(this).load(urlEdit);
                    debugger;
                    $(this).load('@Url.Action("EmpEdit", "Employer")?empId='+idx);
                },
                show: {

                    effect: "blind",
                    duration: 1000
                },

                title: "Update Employer",
                buttons: {
                    "Update": function () {
                       
                        var form = $("#updateForm");
                        $.validator.unobtrusive.parse(form);
                        if (form.valid()) {
                         
                            updateEmployer(idx);
                            alert("Updated Succesfully....");
                            window.location = window.location.href;
                            location.reload();
                            $("#divTable").empty();
                        }
                    }
                    ,
                    "Cancel": function () {
                   
                        $(this).dialog("close");
                    }
                }

            });
            return false;
        });
    });

    
function addEmployer() {
        var tblEmployer = {}
        debugger;
        
        tblEmployer.empFirstname = $("#empFirstname").val();
        tblEmployer.empMiddlename = $("#empMiddlename").val();
        tblEmployer.empLastname = $("#empLastname").val();
        tblEmployer.empGender = $("#empGender").val();
        tblEmployer.empContactno = $("#empContactno").val();
        tblEmployer.empcity = $("#empcity").val();
        tblEmployer.empDescription = $("#empDescription").val();
        tblEmployer.empUsername = $("#empUsername").val();
        tblEmployer.empPassword = $("#empPassword").val();
        tblEmployer.companyId = $("#companyId").val();
        $.ajax({
            url: "Employer/EmpCreate",
            datatype: "json",
            data: "{employer:" + JSON.stringify(tblEmployer) + "}",
            type: "POST",
            contentType: "application/json;charset=utf-8",
            success: function (data) {},
            error: function (err) { alert(err); }

        });

    }


function updateEmployer(idx) {
        var tblEmployer = {}

        tblEmployer.empId = idx;
        tblEmployer.empFirstname = $("#emp_empFirstname").val();
        tblEmployer.empMiddlename = $("#emp_empMiddlename").val();
        tblEmployer.empLastname = $("#emp_empLastname").val();
        tblEmployer.empGender = $("#emp_empGender").val();
        tblEmployer.empContactno = $("#emp_empContactno").val();
        tblEmployer.empcity = $("#emp_empcity").val();
        tblEmployer.empDescription = $("#emp_empDescription").val();
        tblEmployer.empUsername = $("#emp_empUsername").val();
        tblEmployer.empPassword = $("#emp_empPassword").val();
        tblEmployer.companyId = $("#emp_companyId").val();

        $.ajax({
            url: "Employer/EmpEdit",
            datatype: "json",
            data: "{emp:" + JSON.stringify(tblEmployer) + "}",
            type: "POST",
            contentType: "application/json;charset=utf-8",
            success: function (data) {
                $("#divTable").dialog("close");
                },
            error: function (err) { alert(err); }

        });

}
</script>